-- INSTAGRAM TABLES 

CREATE TABLE users (
    id INTEGER AUTO_INCRMENT PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    user_name VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
);

